name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build and install
        run:
          pip install .

      - name: test importability
        run:
          python -E -Wall -bb -c 'import miniaudio'

      - name: pytest
        run: |
          pip install -r requirements-test.txt
          pytest -v tests/
